latest="bionic.git~lineage-22.2"

# If yes, only static linking will be used
static_link=yes

# FIXME: copy a built bionic into the sysroots where's it's expected
cp -ruvp /play/Android/Lineage-22.1/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-gnu-9.3/aarch64-buildroot-linux-gnu/sysroot/* ${local_builds}/sysroot-${target}/
