# Get the latest version
latest="gmp.git~master"

# This is a list of default flags always supplied to configure
default_configure_flags="--enable-cxx --enable-fft"

# If yes, only static linking will be used
static_link=yes

# FIXME: docs won't install without an error
default_makeflags="-i -k"
