#
# This is a table of URLs for checking out development sources.
# NOTE: use spaces instead of TABs
#

# These are infrastructure files and only need to be built once for the host

expat.git      https://github.com/libexpat/libexpat.git
gmp.git        https://github.com/sethtroisi/libgmp.git
mpc.git        https://gitlab.inria.fr/mpc/mpc.git
mpfr.git       https://gitlab.inria.fr/mpfr/mpfr.git
python         http://snapshots.linaro.org/components/toolchain/infrastructure/
# installjammer-1.2.15 http://snapshots.linaro.org/components/toolchain/infrastructure/
linux          http://snapshots.linaro.org/components/toolchain/infrastructure/
libiconv.git	https://git.savannah.gnu.org/git/libiconv.git
# These URLS are for repositories, ie... git
dejagnu.git    https://git.savannah.gnu.org/git/dejagnu.git

# GCC
gcc.git         git://gcc.gnu.org/git/gcc.git
abe.git         https://github.com/rsavoye/abe.git

# Binutils
binutils-gdb.git git://sourceware.org/git/binutils-gdb.git
gdb.git         git://sourceware.org/git/binutils-gdb.git
binutils.git    git://sourceware.org/git/binutils-gdb.git

# Libraries
# eglibc.git      http://git.linaro.org/git/toolchain/eglibc.git
glibc.git       git://sourceware.org/git/glibc.git
newlib.git      https://github.com/bminor/newlib.git
libgloss.git    https://github.com/bminor/newlib.git
bionic.git      https://github.com/LineageOS/android_bionic

qemu.git        https://github.com/qemu/qemu.git

